[project]
name = "wacky-welcome-whatsit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gpiozero>=2.0.1",
    "playsound3>=3.2.3",
]
